#!/bin/sh

getname() {
  cd "$XDG_CONFIG_HOME"/x11/windows || exit 1
  for i in *; do
    watom "$1" WM_NAME | grep -io "$i" 2>/dev/null && break
    watom "$1" _NET_WM_NAME | grep -io "$i" 2>/dev/null && break
  done
}

# See if already exists
case "`getname $1`" in
  mpv*)        grp=1 ;;
  surf*)       wtf "$1" && grp=2 ;;
  browse*)     wtf "$1" && grp=2 ;;
  edit*)       wtf "$1" && grp=3 ;;
  mutt*|news*) wtf "$1" && grp=4 ;;
  irc*)        wtf "$1" && grp=5 ;;
  *docs*)      wtf "$1" && grp=6 ;;
  zathura*)    wtf "$1" && grp=6 ;;
esac

chwso -r "$1"

if [ $grp ]; then
  grp "$grp" "$1"
  "$XDG_DATA_HOME"/x11/groupsbar
fi
