#!/bin/sh

WIN=$XDG_CONFIG_HOME/x11/tags

name="`xprop -id "$1" | awk '/WM_CLASS/{print $NF}' | tr -d '"' `"
awk -v r="$name" '$0 ~ r {print $2, $3}' "$WIN" | while read -r flag tag; do
	if test "$flag" = true; then
		wtf "$flag"
		chwso "$1"
	fi
	if test "$tag" != ""; then
		grp "$tag" "$1"
		/usr/local/share/hwwm/groupsbar
	fi
done
