#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# toggle the fullscreen state of a window
# depends on: focus.sh

FS=$(xprop -root | awk '/FS/{print $3, $4, $5, $6, $7}' | sed 's/\"//g')
if test ${#FS} -gt 0; then
	echo "$FS" | xe -N5 -s 'wtp $1 $2 $3 $4 $5'
	xprop -root -remove FS
	/usr/local/share/hwwm/wshuf
else
	xprop -root -format FS 8s -set FS "$(wattr xywhi $1)"
	. "$XDG_CONFIG_HOME/x11/size"
	wtp "$gaps" "$gaps" "$fulw" "$fulh" "$1"
	chwso -r "$1"
fi

wtf "$1"
