#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# toggle the fullscreen state of a window
# depends on: focus.sh


if watom `lsw -r` FS | xargs -n 5 wtp; then
	xprop -root -remove FS
	/usr/local/share/hwwm/wshuf
else
	xprop -root -format FS 8s -set FS "$(wattr xywhi $1)"
	. "$XDG_CONFIG_HOME/x11/size"
	wtp "$gaps" "$gaps" "$fulw" "$fulh" "$1"
	chwso -r "$1"
fi

wtf "$1"
