#!/bin/sh

GITBAR="$XDG_RUNTIME_DIR/statusbar/git"

comm=0
push=0
pull=0

while IFS="⇄↑↓" read -r input; do
	case "$input" in
		*↑*) push=`echo "$input" | tr -cd [:digit:]` ;;
		*↓*) pull=`echo "$input" | tr -cd [:digit:]` ;;
		*⇄*) comm=`echo "$input" | tr -cd [:digit:]` ;;
	esac		
done < $GITBAR

case "$1" in
	commit) comm=`commit wc` ;;
	pull)   pull=`pull wc`   ;;
	push)   push=`push wc`   ;;
esac

check=0
if [ $comm -gt 0 ]; then
	comm="⇄$comm"
	check=1
else
	comm=""
fi

if [ $push -gt 0 ]; then
	push="↑$push"
	check=1
else
	push=""
fi

if [ $pull -gt 0 ]; then
	pull="↓$pull"
	check=1
else
	pull=""
fi

if [ $check -eq 1 ]; then
	printf '%s\n' " [$push$pull$comm]" > "$GITBAR"
else
	printf '%s\n' "" > "$GITBAR"
fi
