#!/bin/sh

GITBAR="$XDG_RUNTIME_DIR/statusbar/git"

append() {
	count="$(echo "$1" | tr -d "[[:space:]]")" 
	test "$count" -eq 0 && return 
	printf '%s\n' "$count$2"
}

stringify() {
	append "$(wc -l < "$XDG_DATA_DIR/pushes")" "↑"
	append "$(wc -l < "$XDG_DATA_DIR/pulls")" "↓"
	append "$(wc -l < "$XDG_DATA_DIR/commits")" "⇄"
}

# It's messy, but it removes newlines from the three file outputs
tmp="$(stringify | tr -d '\n')"
case "_$tmp" in
	_) echo "" > "$GITBAR"              ;;
	*) printf '[%s]\n' "$tmp" > "$GITBAR" ;;
esac
