#!/bin/sh
#
# Copyright (c) 2015 Greduan <me@greduan.com>, licensed under the WTFPL
# Adds group-like capabilities, sorta like those you find in CWM and such WMs

case "$1" in
  0x0*) grp "$2" "$1"           ;;
  *) lsgrp "$1" | xargs mapw -t ;;
esac
