#!/usr/bin/env bash

# Number of groups
panels=6
declare -a item

for (( i = 1; i <= $panels; i++ )); do
  groups=$(lsgrp "$i")
  if [[ $groups != "" ]]; then
    if wattr m "$(lsgrp "$i" | tail -n 1)"; then
      item[$i]="◉"
    else
      item[$i]="◍"
    fi
  else
    item[$i]="◌"
  fi
  result+=${item["$i"]} 
done

printf '%s\n' "—${result[@]}—" > $XDG_RUNTIME_DIR/statusbar/groups