#!/bin/sh
DIR=/usr/local/share/hwwm

wew | while read -r ev; do
	wid=`echo "$ev" | sed 's/.*://'`
	fullscreen="$(watom `lsw -r` FS 2>/dev/null)"
	case "$ev" in
		# Unmap
		18*)	if test -z $fullscreen; then 
				$DIR/wshuf | xargs -n 5 wtp
				wtf `lsw | tail -n1`
			fi
			$DIR/groupsbar           ;;
		# Map
		19*)	if test -z $fullscreen; then
				$DIR/wshuf | xargs -n 5 wtp
				$DIR/autotag "$wid"
				wtf "$wid"
			fi
			$DIR/groupsbar           ;;
		# Destroy
		17*)	wtf `lsw | tail -n1`
			if test -z $fullscreen; then
				$DIR/wshuf | xargs -n 5 wtp
			else
				xprop -root -remove FS
			fi
			$DIR/groupsbar           ;;
	esac
done
