#!/bin/sh
DIR=/usr/local/share/hwwm

FOCUS_MASK=2097152
wew -m $FOCUS_MASK | while read -r ev; do
	wid=`echo "$ev" | sed 's/.*://'`
	fullscreen="$(watom `lsw -r` FS 2>/dev/null)"
	case "$ev" in
		# Focus in
		9*)	chwb -s 1 -c 3c3836 "$wid" ;;
		# Focus out
		10*) chwb -s 0 "$wid" ;;
		# Unmap
		18*)	if test -z $fullscreen; then 
				$DIR/wshuf | xargs -n 5 wtp
				wtf `lsw | tail -n1`
			fi
			$DIR/groupsbar           ;;
		# Map
		19*)	if test -z $fullscreen; then
				$DIR/wshuf | xargs -n 5 wtp
				$DIR/autotag "$wid"
				wtf "$wid"
			fi
			$DIR/groupsbar           ;;
		# Destroy
		17*)	wtf `lsw | tail -n1`
			test -z $fullscreen || xprop -root -remove FS
			$DIR/wshuf | xargs -n 5 wtp
			$DIR/groupsbar           ;;
	esac
done
