#!/bin/sh
#TODO: This isn't part of hwwm at all, this should be in a seperate repository
# Full credit to @Earnestly.
statusdir="$XDG_RUNTIME_DIR/statusbar"
mkdir -pm0700 "$statusdir"

trap reload USR1

reload() {	
	kill -INT $$
	battery &
	barrun	
}

battery() {
	while :; do
		read -r level < /sys/class/power_supply/BAT0/capacity
		if [ $level -lt 80 ]; then
			printf ' %s%%\n' "$level" > "$statusdir/batt"
		else
			> "$statusdir/batt"
		fi
		sleep 60
	done
}

battery &

# Initialize some data
test -f "$statusdir/rss" && read -r rss < "$statusdir/rss"
test -f "$statusdir/git" && read -r git < "$statusdir/git"
test -f "$statusdir/media" && read -r media < "$statusdir/media"

# This will fail unless you have something set for *desktop in your Xresources!
background="$(xrdb -query | awk '/background/{print $NF}')"
foreground="$(xrdb -query | awk '/desktop/{print $NF}')"

barrun() {
inotifywait -qme close_write --format %f "$statusdir" | while read -r file; do
	if read -r -- "$file" < "$statusdir/$file"; then
		printf -- ' %s %%{c} %s %%{r} %s%s%s \n' "$batt" "$groups" "$rss" "$git" "$media"
		# We inexplicably need to force a redraw here
		/usr/local/share/hwwm/wshuf | xargs -n 5 wtp
	fi
done | lemonbar -F "$foreground" -B "$background" -d -b -f "DejaVu Book:size=10.5" -f "Symbola:size=9.5" -f "FreeSans:size=9.5"
}

barrun
