#!/bin/sh
DIR=$XDG_DATA_HOME/x11

wew | while read -r ev; do
	wid=`echo "$ev" | sed 's/.*://'`
    case "$ev" in
		18*) $DIR/wshuf | xargs -n 5 wtp
			wtf `lsw | tail -n1`
			$DIR/groupsbar           ;;
		19*) $DIR/wshuf | xargs -n 5 wtp
			$DIR/autotag "$wid"
			wtf "$wid"
			$DIR/groupsbar           ;;
		17*) wtf `lsw | tail -n1`
			if watom `lsw -r` FS | grep "$wid"; then
				xprop -root -remove FS
				$DIR/wshuf | xargs -n 5 wtp
			fi
			$DIR/groupsbar           ;;
	esac
done
