#!/bin/sh
# Requires https://github.com/wmutils
#          https://github.com/halfwit/wmgroup
#          https://github.com/halfwit/watom
#          https://github.com/halfwit/binpack	

# directory of files that correlate to window names
WIN="$XDG_CONFIG_HOME"/x11/window

winsize() {
	while read -r id; do
		xprop -id "$id" | grep -q drawterm && continue 
		name="`xprop -id "$id" | awk '/WM_CLASS/{print $NF}' | tr -d '"' `" 
		cmd="`awk -v r="$name" '$0 ~ r {err=1; $1=""; print} END {exit err}' "$WIN" && awk '/default/{$1=""; print}' "$WIN"`"
		printf '%s %s\n' "`eval "$cmd"`" "$id"
	done
}

## Main
# Don't run if we're fullscreen
watom `lsw -r` FS >/dev/null 2>&1 && exit 0

# window dimensions and gap
. "$XDG_CONFIG_HOME"/x11/size
case $screens in
work) lsw | winsize | /usr/local/share/hwwm/work "$width" "$heigh" "$gaps" ;;
3) lsw | winsize | /usr/local/share/hwwm/triplebinpack "$width" "$heigh" "$gaps" ;;
2) lsw | winsize | /usr/local/share/hwwm/doublebinpack "$width" "$heigh" "$gaps" ;;
*) lsw | winsize | binpack -x "$width" -y "$heigh" -g "$gaps" ;;
esac
